### ISSUE TITLE
Non-square artwork is stretched

### ISSUE THREAD

**Issue by davidsharp** [yianL/atom-spotified#11]
This is pretty minor but I think it's worth bringing up. Not all artwork on Spotify is square, Spotify deals with this with cropping, whereas when it shows in tree view 'minimized', atom-spotified stretches the artwork instead.

(Spotify on top, Atom below)
![screen shot 2017-03-20 at 15 17 54](https://cloud.githubusercontent.com/assets/5731838/24106551/2002f65c-0d80-11e7-806d-22a2b62ee0a3.png)

It's not that big of a deal, as it's just a tiny box at the bottom of the window, and quality isn't that important, but it becomes much more apparent when the artwork is 'maximised':

(Atom on the left, Spotify on the right)
![screen shot 2017-03-20 at 15 18 24](https://cloud.githubusercontent.com/assets/5731838/24106554/21e48e7c-0d80-11e7-9ce2-21d3addcdb3e.png)

I'm not sure what the right approach is here, it seems sensible to crop, like Spotify, as it means both minimized and maximized are consistent, but it's also probably not worth the overhead. That being said, when maximised, artwork such as this which is taller than it is wide takes up much more of the tree view, which is _somewhat_ disadvantageous.

**Comment by yianL** [comment]
I see, thanks for the detailed description. I'll find time to work on it this week!

**Comment by yianL** [comment]
Hey @davidsharp, I just published `v.0.8.0`. See if it looks better to you now.

**Comment by davidsharp** [comment]
Much better, thanks :+1:
