### ISSUE TITLE
Breaks on Atom 1.17.0

### ISSUE THREAD

**Issue by ChrisRast** [yianL/atom-spotified#12]
Hi,
I just updated to the latest Atom version, 1.17.0 and the status in the tree view is not displayed anymore. They added some toggle buttons and I suspect the API has changed ?
Anyway, thank you for your work before !

**Comment by yianL** [comment]
Hi Chris,
I just pushed `v.0.8.0` to fix this issue. Give it a shot and see if it works for you.

**Comment by ChrisRast** [comment]
Awesome!
Fixed, thanks!
