### ISSUE TITLE
Spotify keeps on reopening

### ISSUE THREAD

**Issue by lolleko** [yianL/atom-spotified#8]
Even if the View is toggled Spotify keeps on reopening after closing. This is really inconvenient if you want to save battery life.

If this is not a limitation by spotify-node-applescript, you should maybe add an option that prevents Spotify from automatically launching.

**Comment by yianL** [comment]
I believe it's the apple script that's causing Spotify to open again and again. Will look into how to fix it, thanks for reporting this issue!

**Comment by yianL** [comment]
@lolleko Should be fixed in `v0.6.0`, give it a shot and let me know!

**Comment by lolleko** [comment]
Yup works, does not reopen anymore. Thanks a lot!
